theme: jekyll-theme-minimal

title: [HDz Studios.]
description: [Coming soon...]

logo: [D:\Pics nd vids\New folder (2)\splendor.jpg]
show_downloads: ["true"]
google_analytics: [Your Google Analytics tracking ID]
